import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';

import '../../../core/constants/app_constants.dart';
import '../models/transfer_task.dart';

class FileTransferService {
  static const _uuid = Uuid();

  ServerSocket? _server;
  final _updateController =
      StreamController<TransferTask>.broadcast();

  Stream<TransferTask> get onUpdate =>
      _updateController.stream;

  String? _selfId;
  String? _selfName;

  Future<void> startServer({
    required String selfId,
    required String selfName,
  }) async {
    _selfId = selfId;
    _selfName = selfName;

    await _server?.close();

    _server = await ServerSocket.bind(
      InternetAddress.anyIPv4,
      AppConstants.fileTransferPort,
    );

    _server!.listen(
      _handleIncomingConnection,
      onError: (_) {},
    );
  }

  // ---------------------------------------------------------------------------
  // Receiving
  // ---------------------------------------------------------------------------

  Future<void> _handleIncomingConnection(
    Socket socket,
  ) async {
    // Fallback ID only.
    // The real transfer ID is received from the sender's header.
    final fallbackTaskId = _uuid.v4();

    var transferId = fallbackTaskId;

    final headerBytes = <int>[];
    var headerParsed = false;

    IOSink? sink;
    File? file;
    TransferTask? task;

    var received = 0;
    var fileSize = 0;

    final done = Completer<void>();

    late final StreamSubscription<Uint8List> sub;

    sub = socket.listen(
      (chunk) async {
        sub.pause();

        try {
          var offset = 0;

          // ---------------------------------------------------------------
          // Header
          // ---------------------------------------------------------------

          if (!headerParsed) {
            final newlineIndex = chunk.indexOf(10);

            if (newlineIndex == -1) {
              headerBytes.addAll(chunk);
              sub.resume();
              return;
            }

            headerBytes.addAll(
              chunk.sublist(0, newlineIndex),
            );

            offset = newlineIndex + 1;
            headerParsed = true;

            final json =
                jsonDecode(
                  utf8.decode(headerBytes),
                ) as Map<String, dynamic>;

            if (json['tag'] !=
                AppConstants.protocolTag) {
              await sub.cancel();
              socket.destroy();

              if (!done.isCompleted) {
                done.complete();
              }

              return;
            }

            // IMPORTANT:
            // Use the transfer ID generated by the sender.
            transferId =
                json['id'] as String? ??
                    fallbackTaskId;

            final fileName =
                json['fileName'] as String;

            fileSize =
                json['fileSize'] as int;

            final peerName =
                json['name'] as String? ??
                    'Unknown device';

            final peerIp =
                socket.remoteAddress.address;

            // -------------------------------------------------------------
            // Determine destination folder
            // -------------------------------------------------------------

            final dir =
                await _downloadDirectory(
              fileName,
            );

            final safeName =
                _sanitizeFileName(fileName);

            final uniqueName =
                await _uniqueFileName(
              dir,
              safeName,
            );

            file = File(
              '${dir.path}'
              '${Platform.pathSeparator}'
              '$uniqueName',
            );

            sink = file!.openWrite();

            task = TransferTask(
              id: transferId,
              fileName: fileName,
              totalBytes: fileSize,
              transferredBytes: 0,
              direction:
                  TransferDirection.incoming,
              status:
                  TransferStatus.inProgress,
              peerName: peerName,
              peerIp: peerIp,
            );

            _updateController.add(task!);
          }

          // ---------------------------------------------------------------
          // File body
          // ---------------------------------------------------------------

          if (task != null &&
              offset < chunk.length) {
            final body =
                chunk.sublist(offset);

            final remaining =
                fileSize - received;

            final toWrite =
                body.length > remaining
                    ? body.sublist(
                        0,
                        remaining,
                      )
                    : body;

            if (toWrite.isNotEmpty) {
              sink!.add(toWrite);

              received += toWrite.length;

              task = task!.copyWith(
                transferredBytes: received,
              );

              _updateController.add(task!);
            }
          }

          // ---------------------------------------------------------------
          // Transfer completed
          // ---------------------------------------------------------------

          if (task != null &&
              received >= fileSize) {
            await sub.cancel();

            await sink!.flush();
            await sink!.close();

            // Make absolutely sure the file exists.
            final savedFile = file!;

            final actuallySaved =
                await savedFile.exists();

            if (!actuallySaved) {
              throw Exception(
                'File was not found after saving',
              );
            }

            final savedLength =
                await savedFile.length();

            if (savedLength != fileSize) {
              throw Exception(
                'Saved file size does not match '
                'the received file size',
              );
            }

            task = task!.copyWith(
              status:
                  TransferStatus.completed,
              savedPath:
                  savedFile.path,
            );

            _updateController.add(task!);

            // -------------------------------------------------------------
            // IMPORTANT:
            // ACK uses the sender's original transfer ID.
            // The sender waits for exactly this ID.
            // -------------------------------------------------------------

            final ack = jsonEncode({
              'tag':
                  AppConstants.protocolTag,
              'type':
                  'transfer_ack',
              'id':
                  transferId,
              'success':
                  true,
            });

            socket.add(
              utf8.encode('$ack\n'),
            );

            await socket.flush();

            await Future<void>.delayed(
              const Duration(
                milliseconds: 100,
              ),
            );

            await socket.close();

            if (!done.isCompleted) {
              done.complete();
            }

            return;
          }

          sub.resume();
        } catch (e) {
          await sub.cancel();
          await sink?.close();

          _emitFailure(
            transferId,
            task,
            socket,
            e,
          );

          socket.destroy();

          if (!done.isCompleted) {
            done.complete();
          }
        }
      },
      onError: (Object e) async {
        await sink?.close();

        _emitFailure(
          transferId,
          task,
          socket,
          e,
        );

        if (!done.isCompleted) {
          done.complete();
        }
      },
      onDone: () async {
        if (task != null &&
            received < fileSize) {
          await sink?.close();

          task = task!.copyWith(
            status:
                TransferStatus.failed,
            errorMessage:
                'Connection closed before '
                'the transfer finished',
          );

          _updateController.add(task!);
        }

        if (!done.isCompleted) {
          done.complete();
        }
      },
      cancelOnError: true,
    );

    await done.future;
  }

  void _emitFailure(
    String id,
    TransferTask? task,
    Socket socket,
    Object e,
  ) {
    final base = task ??
        TransferTask(
          id: id,
          fileName: 'unknown',
          totalBytes: 0,
          transferredBytes: 0,
          direction:
              TransferDirection.incoming,
          status:
              TransferStatus.inProgress,
          peerName:
              'Unknown device',
          peerIp:
              socket.remoteAddress.address,
        );

    _updateController.add(
      base.copyWith(
        status:
            TransferStatus.failed,
        errorMessage:
            e.toString(),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Android / Windows destination
  // ---------------------------------------------------------------------------

  Future<Directory> _downloadDirectory(
    String fileName,
  ) async {
    if (Platform.isAndroid) {
      final root =
          Directory('/storage/emulated/0');

      final category =
          _categoryForFile(fileName);

      final dir = Directory(
        '${root.path}'
        '${Platform.pathSeparator}'
        '${AppConstants.downloadFolderName}'
        '${Platform.pathSeparator}'
        '$category',
      );

      if (!await dir.exists()) {
        await dir.create(
          recursive: true,
        );
      }

      return dir;
    }

    // Windows / other platforms:
    // Keep the existing app Documents behavior.
    final base =
        await getApplicationDocumentsDirectory();

    final dir = Directory(
      '${base.path}'
      '${Platform.pathSeparator}'
      '${AppConstants.downloadFolderName}',
    );

    if (!await dir.exists()) {
      await dir.create(
        recursive: true,
      );
    }

    return dir;
  }

  String _categoryForFile(
    String fileName,
  ) {
    final extension =
        fileName.contains('.')
            ? fileName
                .split('.')
                .last
                .toLowerCase()
            : '';

    const images = {
      'jpg',
      'jpeg',
      'png',
      'gif',
      'webp',
      'bmp',
      'heic',
      'heif',
      'tiff',
      'svg',
    };

    const videos = {
      'mp4',
      'mkv',
      'avi',
      'mov',
      'wmv',
      'flv',
      'webm',
      '3gp',
      'm4v',
    };

    const audio = {
      'mp3',
      'wav',
      'm4a',
      'aac',
      'flac',
      'ogg',
      'opus',
      'wma',
    };

    const documents = {
      'pdf',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'txt',
      'csv',
      'rtf',
      'zip',
      'rar',
      '7z',
      'tar',
      'gz',
      'json',
      'xml',
    };

    if (images.contains(extension)) {
      return 'Images';
    }

    if (videos.contains(extension)) {
      return 'Videos';
    }

    if (audio.contains(extension)) {
      return 'Audio';
    }

    if (documents.contains(extension)) {
      return 'Documents';
    }

    return 'Other';
  }

  // ---------------------------------------------------------------------------
  // Filename handling
  // ---------------------------------------------------------------------------

  String _sanitizeFileName(
    String original,
  ) {
    var name = original.trim();

    if (name.isEmpty) {
      name = 'file';
    }

    // Remove path separators and
    // Windows-invalid characters.
    name = name.replaceAll(
      RegExp(r'[\\/:*?"<>|]'),
      '_',
    );

    // Prevent traversal.
    name = name.replaceAll(
      '..',
      '_',
    );

    // Remove control characters.
    name = name.replaceAll(
      RegExp(r'[\x00-\x1F]'),
      '_',
    );

    if (name.isEmpty) {
      return 'file';
    }

    return name;
  }

  Future<String> _uniqueFileName(
    Directory dir,
    String original,
  ) async {
    var candidate = original;
    var counter = 1;

    while (
        await File(
          '${dir.path}'
          '${Platform.pathSeparator}'
          '$candidate',
        ).exists()) {
      final dotIndex =
          original.lastIndexOf('.');

      if (dotIndex <= 0) {
        candidate =
            '$original ($counter)';
      } else {
        candidate =
            '${original.substring(0, dotIndex)}'
            ' ($counter)'
            '${original.substring(dotIndex)}';
      }

      counter++;
    }

    return candidate;
  }

  // ---------------------------------------------------------------------------
  // Sending
  // ---------------------------------------------------------------------------

  Future<void> sendFile({
    required String targetIp,
    required String peerName,
    required File file,
    required String fileName,
  }) async {
    final taskId = _uuid.v4();

    final fileSize =
        await file.length();

    var task = TransferTask(
      id: taskId,
      fileName: fileName,
      totalBytes: fileSize,
      transferredBytes: 0,
      direction:
          TransferDirection.outgoing,
      status:
          TransferStatus.inProgress,
      peerName: peerName,
      peerIp: targetIp,
    );

    _updateController.add(task);

    Socket? socket;

    try {
      socket = await Socket.connect(
        targetIp,
        AppConstants.fileTransferPort,
        timeout:
            const Duration(seconds: 10),
      );

      // ---------------------------------------------------------------
      // Listen for receiver ACK.
      // ---------------------------------------------------------------

      final ackCompleter =
          Completer<bool>();

      final subscription =
          socket.listen(
        (data) {
          try {
            final text =
                utf8.decode(data);

            for (final line
                in text.split('\n')) {
              if (line.trim().isEmpty) {
                continue;
              }

              final json =
                  jsonDecode(line)
                      as Map<String, dynamic>;

              if (json['type'] ==
                      'transfer_ack' &&
                  json['id'] == taskId) {
                if (!ackCompleter
                    .isCompleted) {
                  ackCompleter.complete(
                    json['success'] == true,
                  );
                }
              }
            }
          } catch (_) {
            // Ignore malformed ACK data.
          }
        },
        onError: (_) {
          if (!ackCompleter
              .isCompleted) {
            ackCompleter.complete(false);
          }
        },
      );

      final header = jsonEncode({
        'tag':
            AppConstants.protocolTag,
        'type':
            'file_transfer',

        // This is the ID that the receiver
        // MUST return in the ACK.
        'id':
            taskId,

        'name':
            _selfName,
        'fileName':
            fileName,
        'fileSize':
            fileSize,
      });

      socket.add(
        utf8.encode('$header\n'),
      );

      var sent = 0;

      await for (final chunk
          in file.openRead()) {
        socket.add(chunk);

        await socket.flush();

        sent += chunk.length;

        task = task.copyWith(
          transferredBytes: sent,
        );

        _updateController.add(task);
      }

      // ---------------------------------------------------------------
      // IMPORTANT:
      // Do NOT mark completed here.
      // Wait until receiver confirms the file was saved.
      // ---------------------------------------------------------------

      bool receiverConfirmed;

      try {
        receiverConfirmed =
            await ackCompleter.future.timeout(
          const Duration(seconds: 15),
        );
      } on TimeoutException {
        receiverConfirmed = false;
      }

      await subscription.cancel();

      if (receiverConfirmed) {
        task = task.copyWith(
          status:
              TransferStatus.completed,
        );
      } else {
        task = task.copyWith(
          status:
              TransferStatus.failed,
          errorMessage:
              'Receiver did not confirm '
              'that the file was saved',
        );
      }

      _updateController.add(task);
    } catch (e) {
      task = task.copyWith(
        status:
            TransferStatus.failed,
        errorMessage:
            e.toString(),
      );

      _updateController.add(task);
    } finally {
      await socket?.close();
    }
  }

  Future<void> dispose() async {
    await _server?.close();
    await _updateController.close();
  }
}